#!/usr/bin/env bash
libdir()
{
    echo "$(dirname "$(readlink -f "${BASH_SOURCE}")")/lib"
}

. "$(libdir)/support"

init_test_environment

expect_output "docker run --rm $(get_test_image) id" "uid=9001(user) gid=9001(user) groups=9001(user)"
expect_output_contains "docker run --rm -e LOCAL_USER_NAME=root $(get_test_image) id" "uid=0(root) gid=0(root) groups=0(root)"
expect_output "docker run --rm -e LOCAL_USER_NAME=user2 -e LOCAL_USER_UID=1000 $(get_test_image) id" "uid=1000(user2) gid=1000(user2) groups=1000(user2)"